import * as React from "react"
import "../components/hero.css"
import AboutImg from "../../src/images/about-img.jpg";
import SystemImg from "../../src/images/system-img.jpg";
const DigitalProductCom = () => (
  <div className="Digital-product-Section">
    <div className="container  w-[90%] md:w-[90%] p-5 mx-auto my-10">
        <h1 className="text-5xl font-semibold leading-[70px]">digital <br></br> product development</h1>
       

        <div className="container flex flex-col md:flex-row justify-center py-5 my-10">
             <div className="w-full md:w-1/2 p-5">
                <h3 className="text-4xl font-semibold mt-10 p-4 leading-[50px]">We craft enterprise-grade digital products, for your business needs</h3>
             </div>
              <div className="w-full md:w-1/2">
                <p className="text-[18px]">We’ve been building, best-in-class user experiences for our customers since 2016 and we haven’t stopped yet.
                     To date, we’ve successfully deployed 25+ applications, for several different business domains and we are still exploring for more. We have experience across every major industry means that we can build a custom
                     solution to solve any challenge. We know how to create products that would delight our customers and their end-users.</p>
                <p className="text-[18px]">  Beyond expertise across several tools and technologies, we do in-depth analysis of different
                     real world use-cases in all phases of the development lifecycle, which increases our productivity and decreases wastage of efforts.
                      We plan, code, build, test, deploy, monitor, and support at scale, and our products are designed to be future-proof and modular in structure to support any future scope of development.</p>

                <p className="text-[18px]">Our multi-functional team of developers collaborate with designers and product architects at every stage, to keep the development aligned 
                    towards end-user’s usage behaviour. As a result, our products are not only exceptionally built, but offers a seamless user experience.</p>
              </div>
        </div>


        <div className="container flex flex-col md:flex-row justify-center py-5 my-10">
             <div className="w-full md:w-1/2 p-5">
                <h3 className="text-4xl font-semibold mt-10 p-4 leading-[50px]">System design</h3>
                <p className="text-[18px] p-4">Our experienced architects help our clients to brainstorm and evaluate all possibilities to bring their ideas to life. The best user experiences require a stong back-end foundation. Over past years our team have excelled on integrating front-end apps and websites with back-end
                     systems and microservices. We evaluate all possible alternatives depending on cost, go-to-market strategy, performance, scaling, and security considerations.</p>
             </div>
              <div className="w-full md:w-1/2">
                 <img alt="img" src={SystemImg} />
              </div>
        </div>


        <div className="container shadow-lg border border-gray-200 flex flex-col md:flex-row justify-center py-5 my-8">
             <div className="w-full md:w-1/2 p-5 my-5">
                <h3 className="text-4xl font-semibold mt-10 p-4 leading-[50px]">Frontend engineering</h3>
                <p className="text-[18px] p-4">We are obsessed with performance centric web apps and that drives our engineers to achieve a new high when it comes to delivering a high-speed UX. If you have a existing backend 
                system which supports API, we will integrate with that one too..</p>
                 <p className="text-[18px] p-4">With the help of data visualization tools we can help you visualize all the data generated by your business processes, and create dashboards to keep track of pretty much everything.</p>
             </div>
              <div className="w-full md:w-1/2 my-12 p-10">
                 <p className="text-xl mt-10 py-4 font-semibold">EXPERTISE</p>
                 <div className="row grid grid-cols-2">
                    <p className="text-[18px]">React.Js</p>
                    <p className="text-[18px]">Gatsby.Js</p>
                    <p className="text-[18px]">Next.Js</p>
                    <p className="text-[18px]">NodeRED</p>
                    <p className="text-[18px]">D3.Js</p>
                    <p className="text-[18px]">Grafana</p>
                 </div>
              </div>
        </div>




        <div className="container shadow-lg border border-gray-200 flex flex-col md:flex-row justify-center py-5 my-8">
             <div className="w-full md:w-1/2 p-5 my-5">
                <h3 className="text-4xl font-semibold mt-10 p-4 leading-[50px]">Backend engineering</h3>
                <p className="text-[18px] p-4">From the earliest stages of product conception and strategy development, our seasoned architects focus on building robust backend-system to meet your specific needs. Whether it’s integrating with your existing systems or building a custom solution from-scratch, our engineers have done it. We follow the API-First Design approach,
                 which allows any modern front-end framework, library or mobile app to quickly integrate with the backend.</p>
                 
             </div>
              <div className="w-full md:w-1/2 my-12 p-10">
                 <p className="text-xl mt-10 py-4 font-semibold">EXPERTISE</p>
                 <div className="row grid grid-cols-2 gap-1">
                    <p className="text-[18px]">Ruby on Rails</p>
                    <p className="text-[18px]">PostgreSQL</p>
                    <p className="text-[18px]">TimescaleDb</p>
                    <p className="text-[18px]">NodeRED</p>
                    <p className="text-[18px]">Redis</p>
                    <p className="text-[18px]">Node.JS</p>
                    <p className="text-[18px]">MongoDB</p>
                    <p className="text-[18px]">Solr</p>
                    <p className="text-[18px]">Cloud Computing</p>
                 </div>
              </div>
        </div>




        <div className="container shadow-lg border border-gray-200 flex flex-col md:flex-row justify-center py-5 my-8">
             <div className="w-full md:w-1/2 p-5 my-5">
                <h3 className="text-4xl font-semibold mt-10 p-4 leading-[50px]">Mobile app development</h3>
                <p className="text-[18px] p-4">When it comes to mobile app development, you want to go live on both Android Play Store and iOS App Store, but you don’t want to bear extra cost for two separate apps. Thats why Hybrid mobile app frameworks comes to aid with their code once - deploy everywhere feature.
                 Means a single code base that looks and performs exactly same can run on both Android and iOS platform.</p>
                 <p className="text-[18px] p-4">If that’s not your choice, our inhouse Android developers can code-build-deploy native app with ease.</p>
             </div>
              <div className="w-full md:w-1/2 my-12 p-10">
                 <p className="text-xl mt-10 py-4 font-semibold">EXPERTISE</p>
                 <div className="row grid grid-cols-2 gap-1">
                    <p className="text-[18px]">React Native</p>
                    <p className="text-[18px]">Flutter</p>
                    <p className="text-[18px]">Ionic</p>
                    <p className="text-[18px]">Android</p>
                    
                 </div>
              </div>
        </div>


        <div className="container shadow-lg border border-gray-200 flex flex-col md:flex-row justify-center py-5 my-8">
             <div className="w-full md:w-1/2 p-5 my-5">
                <h3 className="text-4xl font-semibold mt-10 p-4 leading-[50px]">Search engine optimization</h3>
                <p className="text-[18px] p-4">Our developers, designers and strategists collaborates with product owners to make the web app search-engine friendly. Means Google and other search engines can crawl each page on the website efficiently, interpret the content effectively, and index it in their database. Once indexed, they can then
                 serve the most relevant and valuable web pages to their users based on the topics they search for on the very first page of the search results.</p>
                 
             </div>
              <div className="w-full md:w-1/2 my-12 p-10">
                 <p className="text-xl mt-10 py-4 font-semibold">EXPERTISE</p>
                 <div className="row grid grid-cols-2 gap-1">
                    <p className="text-[18px]">Google Analytics</p>
                    <p className="text-[18px]">Google AdWords</p>
                    <p className="text-[18px]">Google PageSpeed Index</p>
                   
                    
                 </div>
              </div>
        </div>



        <div className="container shadow-lg border border-gray-200 flex flex-col md:flex-row justify-center py-5 my-8">
             <div className="w-full md:w-1/2 p-5 my-5">
                <h3 className="text-4xl font-semibold mt-10 p-4 leading-[50px]">Security & compliance</h3>
                <p className="text-[18px] p-4">Web application security is the process of protecting websites and online services against different security threats that exploit vulnerabilities in an application’s code. Common targets for web application attacks are content management systems,
                 database administration tools and SaaS applications.</p>
                 <p className="text-[18px]">GEOGO has developed and follows an standard approach to ensure we offer our clients comprehensive 
                    approaches to testing every project before every deployment.</p>
             </div>
              <div className="w-full md:w-1/2 my-12 p-10">
                 <p className="text-xl mt-10 py-4 font-semibold">TACTICS & STRATEGY</p>
                 <div className="row grid grid-cols-2 gap-1">
                    <p className="text-[18px]">SSL</p>
                    <p className="text-[18px]">CSRF Protection</p>
                    <p className="text-[18px]">XSS Prevention</p>
                   
                    
                 </div>
              </div>
        </div>




    </div>
  </div>
)

export default DigitalProductCom
